#!/bin/bash
# Update lib/version.dart with the current git commit SHA
cd "$(dirname "$0")/.."
SHA=$(git rev-parse --short HEAD)
echo "// Generated by tool/update_version.sh" > lib/version.dart
echo "const String gitCommit = '$SHA';" >> lib/version.dart
echo "Updated version.dart to $SHA"
